BBPATH .= ":${LAYERDIR}"

BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "boot-time"
BBFILE_PATTERN_boot-time = "^${LAYERDIR}/"
BBFILE_PRIORITY_boot-time = "20"

LAYERSERIES_COMPAT_boot-time = "scarthgap"
